name: Call reusable echo workflows

on:
  workflow_dispatch:
    inputs:
      message:
        description: Message to pass to echo workflows
        required: false
        default: hello from caller

jobs:
  # echo_from_resuable_workflows_dir:
  #   uses: ./.github/resuable-workflows/echo.yml@main
  #   with:
  #     message: ${{ inputs.message }}

  echo_from_workflows_resuable_dir:
    uses: ./.github/workflows/resuable-workflows/echo.yml
    with:
      message: ${{ inputs.message }}
