name: On Merge (npm-package-test)

on:
  push:
    branches:
      - release-*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20", "22"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
        shell: bash
      - run: npm test
        shell: bash

  publish:
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    outputs:
      published_version: ${{ steps.publish.outputs.npm_published_version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/publish-library-to-npm-trust
        id: publish
        with:
          workdir: "."
          npm_package_scope: "@sidj-thr"
          npm_package_access: "public"

  create-tag:
    needs: [publish]
    if: needs.publish.result == 'success' && needs.publish.outputs.published_version != ''
    permissions:
      contents: write
    uses: ./.github/workflows/create-release-tag.yml
    with:
      repo_name: "npm-package-test"
      published_version: ${{ needs.publish.outputs.published_version }}
