name: Secret Explicit Workflow

on:
  workflow_dispatch:  

jobs:
  check-secrets:
    uses: sidj-thr-org/actions/.github/workflows/explicit-secret.yaml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}