name: Test Git Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    env:
      abcd: ${{ secrets.abcd }}
    steps:
      - name: Print length
        env:
          ABCD: ${{ env.abcd }}
        run: echo "abcd length: ${#ABCD}"
