name: Test Git Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    env:
      ABCD: ${{ secrets.abcd }}
    steps:
      - name: Print length
        run: |
            if [ -z "$ABCD" ]; then
              echo "ABCD is NOT set"
            else
              echo "ABCD is set"
            fi