name: Test Git Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to create
        required: true

perssions:
  contents: write 

jobs:
  create-git-tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: ${{ inputs.tag }}
    steps:
      - uses: sidj-thr-org/actions/.github/actions/create-git-tag@main
        with:
          tag: ${{ env.TAG }}